import type { Metadata } from "next";
import "./globals.css";
import clsx from "clsx";
import Navbar from "./components/shared/navbar/navbar";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import Footer from "./components/shared/footer";
import AnimationProvider from "./components/provider/animation-provider";

export const metadata: Metadata = {
  title: "The Rise Meme",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={clsx("font-cinzel antialiased")}>
        <AnimationProvider>
          <Navbar />
          {children}
          <Footer />
        </AnimationProvider>
      </body>
    </html>
  );
}
